---
# <ansible_base_dir>/group_vars/home.yml

# homebrew_formulae:
#   - azure-cli
#   - serverless # ignore-dependencies
#   - tmux
#   - ruby-install
#   - chruby # post: bashrc section
#   - nvm # post: bashrc section
#   - jq
#   - packer
#   - terraform
#   - vault

homebrew_taps:
  - homebrew/cask-drivers

# homebrew_casks:
#   - 1password # post: install license key
#   - synology-drive # post: run installer
#   - the-hit-list # post: install license key
#   - dropbox
#   - evernote
#   - arduino
#   - handbrake
#   - nordvpn
#   - send-to-kindle
#   - flux
#   - google-chrome
#   - little-snitch # post: install license key
#   - micro-snitch # post: install license key
#   - github
#   - postman
#   - google-cloud-sdk # post: bashrc section
#   - qlmarkdown
#   - docker
#   - vagrant # post: NFS shared folders
#   - virtualbox
#   - virtualbox-extension-pack
#   - iterm2 # post: shell integration

# Custom packages
#   synology notebook
#   epson_wf_3620
#   neooffice
#   xld
#   helix
#   tapedeck
# ssh
# aws
# ruby
# ruby packages
# nodejs
# nodejs packages
# python packages
# shell
# system preferences
