---
# <ansible_base_dir>/group_vars/work.yml

homebrew_formulae:
  - azure-cli
  - serverless # ignore-dependencies
  - tmux
  - ruby-install
  - chruby # post: bashrc section
  - nvm # post: bashrc section
  - jq
  - packer
  - terraform
  - vault

homebrew_taps:
  - homebrew/cask-drivers

homebrew_casks:
  - 1password # post: install license key
  - synology-drive # post: run installer
  - microsoft-office
  - slack
  - google-drive-file-stream
  - aerial
  - firefox
  - flux
  - google-chrome
  - little-snitch # post: install license key
  - micro-snitch # post: install license key
  - github
  - postman
  - google-cloud-sdk # post: bashrc section
  - qlmarkdown
  - docker
  - vagrant # post: NFS shared folders
  - virtualbox
  - virtualbox-extension-pack
  - iterm2 # post: shell integration

# Additonal shell configuration
# DMG packages
# ssh
# aws
# visual studio code?
# system preferences

# packages for other package management systems:
# ruby, node, python

# Custom packages
#   synology notebook
# ssh
# aws
# ruby
# ruby packages
# nodejs
# nodejs packages
# python
# python packages
# shell
# system preferences
