---
# file: roles/bash/tasks/main.yml

- name: Install ~/.bash_profile
  copy:
    src: bash_profile
    dest: "{{ ansible_user_dir }}/.bash_profile"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Base ~/.bashrc
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
  with_items:
    - { regexp: '^# Personal resource file',
                                  line: '# Personal resource file for Bash(1) interactive non-login shells' }
    - { regexp: '^ ',             line: ' ' }
    - { regexp: '^# Useful aliases',
                                  line: '# Useful aliases' }
    - { regexp: '^alias ls=',     line: 'alias ls="ls -G"' }
    - { regexp: '^alias ll=',     line: 'alias ll="ls -lG"' }
    - { regexp: '^alias la=',     line: 'alias la="ls -laG"' }
    - { regexp: '^alias cd..=',   line: 'alias cd..="cd .."' }
    - { regexp: '^alias dev=',    line: 'alias dev="cd ~/Development"' }

- name: Create development directory
  file:
    path: "{{ ansible_user_dir }}/Development"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755
