---
# file: roles/bash/tasks/main.yml

- name: Install ~/.bash_profile
  copy:
    src: bash_profile
    dest: "{{ ansible_user_dir }}/.bash_profile"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Base {{ ansible_user_dir }}/.bashrc
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |
      # Personal resource file for Bash(1) interactive non-login shells

      # Useful aliases
      alias ls="ls -G"
      alias ll="ls -lG"
      alias la="ls -laG"
      alias cd..="cd .."
      alias dev="cd ~/Development"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - base'
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644
    create: yes

- name: Create development directory
  file:
    path: "{{ ansible_user_dir }}/Development"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755
