- name: Install ~/.bash_profile
  copy:
    src: bash_profile
    dest: "{{ ansible_user_dir }}/.bash_profile"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Base ~/.bashrc
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
  with_items:
    - { regexp: '^# Personal environment file',
                                  line: '# Personal environment file for interactive bash subshells' }
    - { regexp: '^alias ll=',     line: 'alias ll="ls - l"' }
    - { regexp: '^alias mycode=', line: 'alias mycode="cd ~/Code"' }
    - { regexp: '^alias mydata=', line: 'alias mydata="cd ~/Data"' }

- name: Create development code directory
  file:
    path: "{{ ansible_user_dir }}/Code"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700

- name: Create development data directory
  file:
    path: "{{ ansible_user_dir }}/Data"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700
