---
os: osx
osx_image: xcode10.2

env:
  - INV=home
  - INV=work

before_install: sudo easy_install pip

install: sudo pip install ansible

script:
  # Check the playbook's syntax
  - ansible-playbook -i ${INV} --syntax-check site.yml

  # Test the playbook
  - ansible-playbook -i ${INV} site.yml

  # Test the playbook's idempotence
  - idempotence=$(mktemp)
  - ansible-playbook -i ${INV} site.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
