#!/usr/bin/env bash

set -Eeuo pipefail

TRACE=${TRACE:-}
[[ "$TRACE" ]] && set -x

function install_homebrew() {
    if [[ -x "$(command -v /usr/local/bin/brew)" ]]
    then
        echo Homebrew already installed
    else
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
    fi
}

function install_ansible() {
    if brew ls --versions ansible > /dev/null 2>&1
    then
        echo Homebrew ansible formula already installed
    else
        brew install ansible
    fi
}

#
# Create a macOS keychain entry and password lookup file for the Ansible Vault password
#
function install_ansible_vault_password() {
    local ACCOUNT_NAME="macos-infra"
    local SERVICE="Ansible Vault"

    if /usr/bin/security find-generic-password -a "$ACCOUNT_NAME" -s "$SERVICE" > /dev/null 2>&1
    then
        echo Keychain entry for Ansible Vault password already installed
    else
        /usr/bin/security add-generic-password -a "$ACCOUNT_NAME" -s "$SERVICE" -w
    fi

    local VAULT_PASSWORD_FILE="./vault_password_file"

    if [[ ! -e "$VAULT_PASSWORD_FILE" ]]
    then
	cat << EOF > "$VAULT_PASSWORD_FILE"
#!/usr/bin/env bash

/usr/bin/security find-generic-password -a "$ACCOUNT_NAME" -s "$SERVICE" -w
EOF

        chmod +x "$VAULT_PASSWORD_FILE"
    fi
}

function main() {
    install_homebrew
    install_ansible

    git clone https://github.com/andrewdavidbell/macos-infra.git
    cd ./macos-infra

    # install_ansible_vault_password
    echo "Copy sensitive data into staging area"
    echo "Then run:"
    echo "/usr/local/bin/ansible-playbook -K -i <home|work|client> site.yml -v"
}

main
