# Top level playbook to automate configuration of macOS-based machine

---
- name: Provision macOS-based machine
  hosts: macos

  roles:
    - role: macos-customisation

    # macOS applications
    - role: synology
    - role: 1password
    - role: thehitlist
    - role: flux
    - role: snitch

    # Development
    - role: github
    - role: arduino

    # DevOps
    - role: virtualbox
    - role: hashicorp
    - role: docker
