# Top level playbook to automate configuration of macOS-based machine

---
- name: Provision macOS-based machine
  hosts: macos

  pre_tasks:
    - name: Install Homebrew
      script: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      args:
        creates: /usr/local/bin/brew

  roles:
    - role: macos-customisation
    - role: github
