# Top level playbook to automate configuration of macOS-based machine

---
- name: Provision macOS-based machine
  hosts: macos

  roles:
    - role: macos-customisation
  #  - role: synology
  #  - role: 1password
  #  - role: flux
  #  - role: thehitlist
  #  - role: github
  #  - role: arduino
  #  - role: virtualbox
