---
- hosts: all

  roles:
    - role: zsh
      tags: zsh

    - role: homebrew
      tags: homebrew

    - role: ssh
      tags: ssh

  tasks:
    - name: Create source code directory
      file:
        path: "{{ ansible_user_dir }}/Local Source"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: staff
        mode: 0755

    - name: Create soft link to source code directory
      file:
        src: "{{ ansible_user_dir }}/Local Source"
        dest: "{{ ansible_user_dir }}/Documents/Local Source"
        state: link
        owner: "{{ ansible_user_id }}"
        group: staff
        mode: 0755

    - name: Alias to source code directory
      lineinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        regexp: '^alias src='
        insertafter: '# Additional configuration'
        line: 'alias src="cd ~/Documents/Local Source"'

    # - name: Apply Vim configuration
    #   blockinfile:
    #     dest: "{{ ansible_user_dir }}/.vimrc"
    #     block: |
    #       " enable syntax highlighting
    #       syntax on
    #       syntax enable

    #       " enable auto indenation and spaces only
    #       set expandtab
    #       set tabstop=2
    #       set smartindent

    #       " set line numbers for quicker navigation in vim
    #       set number
    #       set cursorline

    #       " enable mouse scrolling
    #       set mouse=a
    #     marker: '" {mark} ANSIBLE MANGED BLOCK'
    #     create: yes

