---
# Top level playbook to automate configuration of macOS-based machine

- import_playbook: base.yml

- import_playbook: home.yml
  when: ansible_model == "Macmini6,2"

- import_playbook: work.yml
  when: ansible_model == "MacBookPro11,5"

- import_playbook: development.yml
