---
# Top level playbook to automate configuration of macOS-based machine

- import_playbook: base.yml

- import_playbook: home.yml
  when: '"Macmini" in ansible_model'

- import_playbook: work.yml
  when: '"MacBookPro" in ansible_model'

- import_playbook: development.yml
