---
# file: roles/awscli/tasks/main.yml

- name: Install AWS CLI
  homebrew:
    name: awscli
    state: present

- name: Ensure {{ ansible_user_dir }}/.aws directory exists
  file:
    path: "{{ ansible_user_dir }}/.aws"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

- name: Check if config dir exists
  local_action: stat path="{{ aws_config_dir }}"
  register: dir

- name: Install AWS config file from fragments
  assemble:
    src: "{{ aws_config_dir }}/config.d"
    dest: "{{ ansible_user_dir }}/.aws/config"
    ignore_hidden: yes
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0600
  when: dir.stat.exists

- name: Install aws aliases for zsh
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: '^ aws'
    insertafter: '# ANSIBLE MANAGED: Antigen'
    line: '  aws'

