---
# file: roles/awscli/tasks/main.yml

- name: Install AWS CLI
  homebrew:
    name: awscli
    state: present

- name: Ensure {{ ansible_user_dir }}/.aws directory exists
  file:
    path: "{{ ansible_user_dir }}/.aws"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

- name: Install AWS config file from fragments
  assemble:
    src: "{{ awscli_staging_dir }}/config.d"
    dest: "{{ ansible_user_dir }}/.aws/config"
    ignore_hidden: yes
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0600

- name: Install AWS credentials file from fragments
  assemble:
    src: "{{ awscli_staging_dir }}/credentials.d"
    dest: "{{ ansible_user_dir }}/.aws/credentials"
    ignore_hidden: yes
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0600

- name: Install aws aliases for zsh
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: '^ aws'
    insertafter: '# ANSIBLE MANAGED: Antigen'
    line: '  aws'

