---
# file: roles/awscli/tasks/main.yml

- name: Install AWS CLI
  homebrew:
    name: awscli
    state: present

- name: Ensure {{ ansible_user_dir }}/.aws directory exists
  file:
    path: "{{ ansible_user_dir }}/.aws"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

# These fragments are ignored by git to prevent leaking of secrets into source
- name: Install AWS config file from fragments
  assemble:
    src: "{{ role_path }}/files/config.d"
    dest: "{{ ansible_user_dir }}/.aws/config"
    ignore_hidden: yes
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0600

# These fragments are ignored by git to prevent leaking of secrets into source
- name: Install AWS credentials file from fragments
  assemble:
    src: "{{ role_path }}/files/credentials.d"
    dest: "{{ ansible_user_dir }}/.aws/credentials"
    ignore_hidden: yes
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0600
