- name: Install The Hit List
  homebrew_cask:
    name: the-hit-list
    state: present

- name: Set licensee name
  osx_defaults:
    domain: com.potionfactory.TheHitList
    key: licenseeName
    type: string
    value: "{{ thehitlist.licensee_name }}"
    state: present
  no_log: True

- name: Set license key
  osx_defaults:
    domain: com.potionfactory.TheHitList
    key: licenseKey
    type: string
    value: "{{ thehitlist.license_key }}"
    state: present
  no_log: True
