---
# <ansible_base_dir>/roles/nodejs/tasks/main.yml

- name: Install NodeJS
  homebrew:
    name: node
    state: "{{ nodejs_state }}"

- name: Install packages for NodeJS
  npm:
    name: "{{ item.name | default(item) }}"
    global: yes
  loop: "{{ nodejs_packages }}"
  tags: nodejs_packages
