---
# <ansible_base_dir>/roles/python/tasks/main.yml

- name: Install Python 3
  homebrew:
    name: python
    state: "{{ python_state }}"

- name: Install packages for Python 3
  pip:
    name: "{{ item.name | default(item) }}"
    executable: /usr/local/bin/pip3
  loop: "{{ python_packages }}"
  tags: python_packages

- name: Add alias for virtualenv using Python 3 (zsh)
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: '^alias venv='
    line: 'alias venv="/usr/local/bin/python3 -m venv --system-site-packages .venv"'
