# Already installed because it's an Ansible dependency
- name: Install Python 2
  homebrew:
    name: python
    state: present

- name: Install Python 3
  homebrew:
    name: python3
    state: present

- name: Install virtualenv
  pip:
    name: virtualenv

- name: Install virtualenvwrapper
  pip:
    name: virtualenvwrapper

- name: Install autopep8
  pip:
    name: autopep8

- name: Make directory for Python workspace
  file:
    path: "{{ ansible_user_dir }}/Code/python"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700

- name: Add alias for virtualenv
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^alias venv='
    line: 'alias venv="virtualenv --system-site-packages .env"'
    create: yes
