---
# <ansible_base_dir>/roles/zsh/tasks/main.ym

# Install Oh My Zsh and manage it's plugins with antigen
# https://github.com/zsh-users/antigen

- name: Install antigen
  homebrew:
    name: antigen
    state: present

- name: Install {{ ansible_user_dir }}/.zshrc
  copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644
