---
# file: roles/vagrant/tasks/main.yml

- name: Install Vagrant
  homebrew_cask:
    name: vagrant
    state: present

- name: Vagrant root privilege for NFS shared folders
  copy:
    src: vagrant_nfs
    dest: /private/etc/sudoers.d/vagrant_nfs
    owner: root
    group: wheel
    mode: 0440
  become: true

- name: Install Packer
  homebrew:
    name: packer
    state: present

- name: Install Terraform
  homebrew:
    name: terraform
    state: present

- name: Install Vault
  homebrew:
    name: vault
    state: present
