---
# file: roles/github/tasks/main.yml

- name: Install git
  homebrew:
    name: git
    state: present

- name: We're not using a Github API token for Homebrew
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^export HOMEBREW_NO_GITHUB_API'
    line: 'export HOMEBREW_NO_GITHUB_API=1'
    create: yes

- name: Set name in global git configuration
  git_config:
    name: user.name
    scope: global
    value: Andrew Bell

- name: Set email in global git configuration
  git_config:
    name: user.email
    scope: global
    value: "{{ github.noreply_user_email }}"

- name: Set page in global git configuration
  git_config:
    name: core.pager
    scope: global
    value: less -r

- name: Ensure .config/git directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/git"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

- name: Install ignore in global git configuration
  copy:
    src: ignore
    dest: "{{ ansible_user_dir }}/.config/git/ignore"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Check for github entry in keychain
  command: >
    /usr/bin/security find-internet-password
    -a {{ github.keychain.account }}
    -s {{ github.keychain.server }}
  register: result
  ignore_errors: true
  changed_when: false

- name: Add github entry to keychain
  command: >
    /usr/bin/security add-internet-password
    -a {{ github.keychain.account }}
    -s {{ github.keychain.server }}
    -w {{ github.keychain.password }}
    -r {{ github.keychain.protocol }}
  when: result|failed
  no_log: true
