---
# <ansible_base_dir>/roles/git/tasks/main.yml

- name: Install git
  homebrew:
    name: git
    state: present

# - name: We're not using a Github API token for Homebrew (bash)
#   lineinfile:
#     path: "{{ ansible_user_dir }}/.bashrc"
#     regexp: '^export HOMEBREW_NO_GITHUB_API'
#     line: 'export HOMEBREW_NO_GITHUB_API=1'

# - name: We're not using a Github API token for Homebrew (zsh)
#   lineinfile:
#     path: "{{ ansible_user_dir }}/.zshrc"
#     regexp: '^export HOMEBREW_NO_GITHUB_API'
#     line: 'export HOMEBREW_NO_GITHUB_API=1'

- name: Set name in global git configuration
  git_config:
    name: user.name
    scope: global
    value: Andrew Bell

- name: Set github email in global git configuration
  git_config:
    name: user.email
    scope: global
    value: "{{ github_email }}"

- name: Set page in global git configuration
  git_config:
    name: core.pager
    scope: global
    value: less -r

- name: Ensure .config/git directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/git"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

- name: Install ignore in global git configuration
  copy:
    src: ignore
    dest: "{{ ansible_user_dir }}/.config/git/ignore"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644
