---
# <ansible_base_dir>/roles/homebrew/tasks/main.yml

# Force homebrew update

- name: Ensure configured taps (formula repositories) are installed
  homebrew_tap:
    tap: "{{ item.name | default(item) }}"
    url: "{{ item.url | default(omit) }}"
    state: present
  loop: "{{ homebrew_taps }}"

- name: Ensure configured casks are installed
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
    accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
  loop: "{{ homebrew_casks }}"
