---
# <ansible_base_dir>/roles/homebrew/tasks/main.yml

# Force homebrew update

- name: Ensure configured taps (formula repositories) are installed
  homebrew_tap:
    tap: "{{ item.name | default(item) }}"
    url: "{{ item.url | default(omit) }}"
    state: present
  loop: "{{ homebrew_taps }}"
  tags: homebrew_taps

- name: Ensure configured casks are installed
  include_tasks:
    file: casks.yml
    apply:
      tags: homebrew_casks
  loop: "{{ homebrew_casks }}"
  loop_control:
    loop_var: cask_item
  tags: homebrew_casks

- name: Ensure configured homebrew formulae are installed
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  loop: "{{ homebrew_formulae }}"
  tags: homebrew_formulae

- name: Additional provisioning for formulae
  include_role:
    name: "{{ item.role }}"
    apply:
      tags: homebrew_formulae_additional
  when: item.role is defined
  loop: "{{ homebrew_formulae }}"
  tags: homebrew_formulae_additional
