---
# file: roles/macos_customisation/tasks/main.yml

###############################################################################
# Language & Region                                                           #
###############################################################################

- name: Set Preferred language
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - en-AU
    state: present

- name: Set Region
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: en_AU
    state: present

###############################################################################
# Date & Time                                                                 #
###############################################################################

- name: Set Time Zone
  command: systemsetup -settimezone "Australia/Melbourne"
  become: true
  changed_when: false

- name: Set Clock to be digital
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: IsAnalog
    type: boolean
    value: false
    state: present

- name: Flash the time separators
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: FlashDateSeparators
    type: boolean
    value: false
    state: present

- name: Set Clock format
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: "EEE HH:mm"
    state: present

###############################################################################
# Trackpad                                                                    #
###############################################################################

- name: Enable 'Tap to click' trackpad preference
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: integer
    value: 1
    state: present

- name: Enable 'Tap to click' trackpad driver preferences
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: integer
    value: 1
    state: present

- name: Enable 'Tap to click' in Trackpad preferences panel
  osx_defaults:
    host: currentHost
    key: com.apple.mouse.tapBehavior
    type: integer
    value: 1
    state: present

- name: Enable 'Secondary click' trackpad preferences
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadRightClick
    type: boolean
    value: true
    state: present

- name: Enable 'Secondary click' trackpad driver preferences
  osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: boolean
    value: true
    state: present

- name: Enable 'Secondary click' in Trackpad preference panel
  osx_defaults:
    host: currentHost
    key: com.apple.trackpad.enableSecondaryClick
    type: boolean
    value: true
    state: present

- name: Show battery percentage
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: "YES"
    state: present
  when: ansible_model == "MacBookPro11,5"

###############################################################################
# Safari                                                                      #
###############################################################################

- name: Open with all windows from last session
  osx_defaults:
    domain: com.apple.Safari
    key: AlwaysRestoreSessionAtLaunch
    type: boolean
    value: true
    state: present

- name: Ask websites not to track me
  osx_defaults:
    domain: com.apple.Safari
    key: SendDoNotTrackHTTPHeader
    type: boolean
    value: true
    state: present

- name: Disable AutoFill Contacts
  osx_defaults:
    domain: com.apple.Safari
    key: AutoFillFromAddressBook
    type: boolean
    value: false
    state: present

- name: Disable AutoFill Passwords
  osx_defaults:
    domain: com.apple.Safari
    key: AutoFillPasswords
    type: boolean
    value: false
    state: present

- name: Disable AutoFill Credit cards
  osx_defaults:
    domain: com.apple.Safari
    key: AutoFillCreditCardData
    type: boolean
    value: false
    state: present

- name: Disable AutoFill Other forms
  osx_defaults:
    domain: com.apple.Safari
    key: AutoFillMiscellaneousForms
    type: boolean
    value: false
    state: present

