---
# file: roles/virtualbox/tasks/main.yml

- name: Install VirtualBox
  homebrew_cask:
    name: virtualbox
    state: "{{ virtualbox.state }}"

- name: Install VirtualBox Extension Pack
  homebrew_cask:
    name: virtualbox-extension-pack
    state: "{{ virtualbox.state }}"
