- name: Install Tap for Synology applications
  homebrew_tap:
    name: caskroom/drivers
    state: present

- name: Install Synology Cloud Station
  homebrew_cask:
    name: synology-cloud-station-drive
    state: present

- name: Check if Synology Note Station is installed
  stat:
    path: "{{ synology.note_station_installed_app }}"
  register: note_station

- name: Attach Synology Note Station Disk Image
  command: hdiutil attach {{ synology.note_station_disk_image }}
  when: note_station.stat.exists == False

- name: Install Synology Note Station
  command: cp -a {{ synology.note_station_mounted_app }} {{ synology.note_station_installed_app }}
  when: note_station.stat.exists == False

- name: Detach Synology Note Station Disk Image
  command: hdiutil detach {{ synology.note_station_mount_point }}
  when: note_station.stat.exists == False
