---
# <ansible_base_dir>/roles/iterm2/tasks/main.yml

- name: Install iTerm2
  homebrew_cask:
    name: iterm2
    state: "{{ iterm2_state }}"

- name: Fetch iTerm2 zsh integration script
  get_url:
    url: https://iterm2.com/shell_integration/zsh
    dest: "{{ ansible_user_dir }}/.iterm2_shell_integration.zsh"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755
    validate_certs: no

- name: Load iTerm2 zsh integration script
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: '^\[\[ -e "${HOME}/.iterm2_shell_integration.zsh" \]\]'
    insertafter: '# Additional configuration'
    line: '[[ -e "${HOME}/.iterm2_shell_integration.zsh" ]] && source "${HOME}/.iterm2_shell_integration.zsh"'
