---
# file: roles/ruby/tasks/main.yml

- name: Install Ruby
  command: ruby-install ruby {{ ruby.version }}

- name: Install Bundler in that stable version of Ruby
  shell: |
    [ -s /usr/local/opt/chruby/share/chruby/chruby.sh ] && . /usr/local/opt/chruby/share/chruby/chruby.sh
    chruby_use {{ ansible_user_dir }}/.rubies/ruby-{{ ruby.version }}
    gem install bundler
    chruby_reset
  args:
    executable: /bin/bash

- name: Useful aliases for Bundler
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    block: |
      alias b="bundle"
      alias bi="b install --path vendor"
      alias bil="bi --local"
      alias bu="b update"
      alias be="b exec"
      alias binit="bi && b package && echo 'vendor/ruby' >> .gitignore"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - bundler'
    create: yes
