---
# <ansible_base_dir>/roles/ruby/tasks/main.yml

- name: Install Ruby
  homebrew:
    name: ruby
    state: "{{ ruby_state }}"

- name: Useful aliases for Bundler
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc"
    block: |
      alias b="bundle"
      alias bi="b install --path vendor"
      alias bil="bi --local"
      alias bu="b update"
      alias be="b exec"
      alias binit="bi && b package && echo 'vendor' >> .gitignore"

      export PATH="${HOMEBREW_PREFIX}/opt/ruby/bin:$PATH"
      export PATH="${HOMEBREW_PREFIX}/lib/ruby/gems/2.6.0/bin/:$PATH"
    marker: '# {mark} ANSIBLE MANAGED BLOCK - bundler'
    create: yes
